---
title: "Printed Markets - The Basel Avisblatt (1729-1845)"
---

"Printed Markets" is a Swiss [research project (see also avisblatt.ch)](https://avisblatt.ch) on a new form of marketplace that emerged in Europe during the seventeenth and, for the most part, in the eighteenth century: the printed advertising market of the so-called "Intelligenzblätter" (intelligencers).
Using the example of the Basel Avisblatt (published 1729-1844/45), "Printed Markets" employs **digital history** and **data science** methods to systematically open up an extensive serial source, to shine a light on the socioeconomic transformations of the "Sattelzeit": The Avisblatt reflects myriads of ways to organise economic exchange, to interlink persons of complementary interests, to spin the socioeconomic web of a town in transition, from early modernity to the industrial age.


## Digital History & Digital History









"Printed Markets" is a project of the Department of History at the University of Basel and is financed by the Swiss National Science Foundation SNSF. The project is led by Prof. Dr. Susanna Burghartz.